baseURL = "https://www.marekdlugos.com/"
languageCode = "en-us"
title = "Marek Dlugos — Revenue Growth, Product, Design, Software Engineering."
disableKinds = ["taxonomy", "taxonomyTerm"]
publishDir = "docs"
disableHugoGeneratorInject = true
SectionPagesMenu = "main"

[minify]
  minifyOutput = true